---
title: "Reproducible Document"
author: "Emma"
format: html
editor_options: 
  chunk_output_type: console
---

## Setup

```{r setup}
#| message: false
#| warning: false

library(tidyverse)

post_meal_data = read.csv2(here::here("data/post-meal-insulin.csv"))

```


## Writing R code 

```{r}
2+2

```

## About me
- Emma
- SDU

My name is **Emma** and i live in *odense*. 

## Simple code
```{r}
3*3
```

## Testing for git

The weather is shit

## Showing the data
```{r}
post_meal_data

glimpse(post_meal_data)

```

## Plot one continues variable 
```{r}
#| fig-cap: "Distribution of BMI."
#| label: fig-bmi-histo

ggplot(post_meal_data, aes( x = BMI)) +
  geom_histogram()

```

In figure @fig-bmi-histo you can see the BMI in a histogram

## Exercise: Discrete plots 

```{r}
#| fig-cap: "Barplot of Group"
#| label: fig-group-bar
ggplot(post_meal_data, aes(x = Group)) +
  geom_bar()

```
See @fig-group-bar above for a cool plot!

## plotting two discrete variables

```{r}

ggplot(post_meal_data, aes (x = Group, fill = as.character (glykemi))) +
  geom_bar( position = position_dodge()) 

```

## Side by side plots

```{r fig-bmi-glycemia}
#| fig-cap: "BMI and glycemia, side by side"
#| fig-subcap: 
#| - "Distribution of BMI"
#| - "Number of those with glycemia"
#| layout-ncol: 2

ggplot(post_meal_data, aes(x = BMI)) +
  geom_histogram()
ggplot(post_meal_data, aes (x = glykemi)) +
  geom_bar()

```

